### ISSUE TITLE
src/finance/loan.cto

### ISSUE THREAD

**Issue by chainbelow** [accordproject/models#34]
There's a typo in the properties of the concept Loan, lein should be lien.

**Comment by mttrbrts** [comment]
@jeromesimeon this is a good opportunity to fix the version conventions so that we can make this change

**Comment by jeromesimeon** [comment]
Agreed @mttrbrts

**Comment by mttrbrts** [comment]
See #15 for a proposal to address this issue

**Comment by mttrbrts** [comment]
Hi @chainbelow , this issue is now resolved in [loan@0.2.0.cto](https://models.accordproject.org/finance/loan@0.2.0.html).

Thanks for your contribution, I hope to see some more!
