### ISSUE TITLE
Markdown or CommonMark?

### ISSUE THREAD

**Issue by jeromesimeon** [accordproject/models#51]
Should the CTO model for CommonMark be renamed to `commonmark.cto` for consistency with  https://github.com/accordproject/markdown-transform ?

**Comment by dselman** [comment]
I vote that yes, we do the rename.

**Comment by jeromesimeon** [comment]
The latest version of the CommonMark and CiceroMark CTO models have been republished/renamed at:
https://models.accordproject.org/markdown/ciceromark.html
https://models.accordproject.org/markdown/commonmark.html

in #51
