### ISSUE TITLE
Logo update to match techdocs

### ISSUE THREAD

**Issue by peterhunn** [accordproject/models#80]
**Describe the bug**
Logo on models page (models.accordproject.org) should be updated to be consistent with the new logo on techdocs page (docs.accordproject.org).

**Comment by CoryWritesCode** [comment]
I can take this if no one else has!

**Comment by CoryWritesCode** [comment]
@irmerk how does one serve to the browser so I can see the what I've changed? Also in your contributing guide, you mention to run tests but there is no test running script or dependencies. Not sure what to do with that.,

**Comment by irmerk** [comment]
Right, I think the `CONTRIBUTING` for this repo in particular could be better tailored.

@jeromesimeon I think would be helpful on updating the site for this repo. We use [Nunjucks](https://mozilla.github.io/nunjucks/) here, so those docs would be helpful.
